on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run tests

jobs:
  test:
    name: Run tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          auto-activate-base: false

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Install dependencies
        shell: bash -l {0}
        run: mamba install cxx-compiler s2geometry libabseil cmake

      - name: Configure s2geography
        shell: bash -l {0}
        run: |
          cmake -S . -B build \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DS2GEOGRAPHY_BUILD_TESTS=ON \
            -DS2GEOGRAPHY_S2_SOURCE=CONDA

      - name: Build s2geography
        shell: bash -l {0}
        run: |
          cmake --build build --config Release

      - name: Run tests
        shell: bash -l {0}
        run: |
          cd build
          ctest -T test --output-on-failure .
