on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run tests

jobs:
  test:
    name: Run tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: s2geography-dev
          use-mamba: true

      - name: Set cache number
        id: cache-number
        shell: bash -l {0}
        # cache will last 3 days by default
        run: echo CACHE_NUMBER=`expr $(date +'%d%m') / 3` >> $GITHUB_ENV

      - name: Set environment file
        id: env-file
        shell: bash -l {0}
        run: echo "env_file=ci/environment.yml" >> $GITHUB_ENV

      - name: Check environment variables
        id: check-env
        run: |
          echo "env.CACHE_NUMBER: ${{ env.CACHE_NUMBER }}"
          echo "env.env_file: ${{ env.env_file }}"

      - name: Cache environment
        uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/s2geography-dev
          key: ${{ runner.os }}-conda-${{ hashFiles( env.env_file ) }}-${{ env.CACHE_NUMBER }}
        id: conda-cache

      - name: Update environment
        run: mamba env update -n s2geography-dev -f ${{ env.env_file }}
        if: steps.conda-cache.outputs.cache-hit != 'true'

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Configure s2geography
        shell: bash -l {0}
        run: |
          cmake -S . -B build \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DS2GEOGRAPHY_BUILD_TESTS=ON \
            -DS2GEOGRAPHY_S2_SOURCE=CONDA

      - name: Build s2geography
        shell: bash -l {0}
        run: |
          cmake --build build --config Release

      - name: Run tests
        shell: bash -l {0}
        run: |
          cd build
          ctest -T test --output-on-failure .
